{% set name = "lumen" %}
{% set version = "0.8.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd4d59ef441040a0b5d0432969ab5343a268b5c01a7da5c4e30ff0bfbaa451c2

build:
  noarch: python
  number: 0
  entry_points:
    - lumen = lumen.command:main
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - panel >=1.6.1
    - hvplot
    - holoviews >=1.17
    - pandas
    - packaging
    - intake <2
    - jinja2 >3.0
    - pyyaml
    - param >=1.9.0

test:
  imports:
    - lumen
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - lumen --help

about:
  home: https://github.com/holoviz/lumen
  summary: Illuminate your data.
  description: |
    Lumen is a fully open-source and extensible agent based framework
    for chatting with data, text-to-SQL and for retrieval augmented
    generation (RAG). It implements a declarative specfication for
    expressing data pipelines, visualizations and dashboards.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://lumen.holoviz.org/
  dev_url: https://github.com/holoviz/lumen

extra:
  recipe-maintainers:
    - hoxbro
    - philippjfr
